# Generated by Django 3.1.3 on 2020-11-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
                ('second_text', models.CharField(max_length=400)),
                ('button_rendered_link', models.CharField(max_length=400)),
            ],
        ),
    ]
