# Generated by Django 3.1.3 on 2020-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAPI', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
