# Generated by Django 3.1.3 on 2020-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAPI', '0003_advertisement_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
