# Generated by Django 3.1.3 on 2020-11-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adAPI', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='advertisements',
            field=models.ManyToManyField(to='adAPI.Advertisement'),
        ),
    ]
