name: Lint

on: [push]

jobs:
  lint-python:
    name: Python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint Python with flake8
      run: |
        pip install flake8 pep8-naming >/dev/null 2>&1
        flake8 . --ignore=E111,E114,E121,E124,E125,E126,E127,E128,E129,E131,E133,W503,W504 --max-line-length=99 --show-source